export const ActionTypes = {
  SET_STUDENTS: "SET_STUDENTS",
  SET_FORM_DATA: "SET_FORM_DATA",
  SET_STUDENT_DATA: "SET_STUDENT_DATA",
  SET_STUDENT_DETAILS:"SET_STUDENT_DETAILS",
  SET_LOGIN_DETAILS:"SET_LOGIN_DETAILS",
  SET_REGISTRATION_DETAILS:"SET_REGISTRATION_DETAILS"
};
